### ISSUE TITLE
Nodemon or webpack for reloading api after file changes would be nice.

### ISSUE THREAD

**Issue by dashcraft** [OfAshAndFire/np_services#2]
Needs to recognize file changes
and restart server as necessary

**Comment by chris-tse** [comment]
I think let's start with nodemon since it's easiest and then look into webpack if we really feel like we need it. I think webpack will unnecessarily bundle stuff, unless you can turn that off somehow.

**Comment by dashcraft** [comment]
Sounds fantatic. Yeah, ideally we just need babel for the es6 stuff (if that's even necessary) and something to reload files on change.

Sounds great!
